### ISSUE TITLE
[VALUES] Heroic Strike Threat with Finkles Skinner

### ISSUE THREAD

**Issue by Truank** [dfherr/ThreatClassic2#29]
### What spell(s) are affected? Please provide any relevant spell IDs/spell names.
I believe there is an issue with heroic strike producing less threat than indicated by the threat meter when using Finkle's Skinner.

### If reporting your findings, please describe your methodology. If you've observed behavior that you feel is not in line with current values, please describe it.
 I base this off of 2 attempts on Vael with finkle's trying to maximize heroic strike threat as a tank where the threat meter indicated a significant threat lead and yet others were gaining aggro over me.

### Please provide any data you have gathered and/or evidence of any observed behavior below. If pertinent, please provide any sources that may back up your research / observations.
This is a clip of the threat meter showing the situation. Both this meter and Tiny Threat seemed to have the same issue.
https://clips.twitch.tv/MiniatureRoundPhoneKappa

### Any additional information?
The 2nd time I saw the issue was obfuscated by a taunt that threw the threat meter off but prior to the taunt there was a substantial threat lead and still aggro was given to someone other than myself who was showing with the substantial lead.

**Comment by dfherr** [comment]
Have all of the people involved the latest version?

This looks pretty much like a delayed sync from Fhynnx (e.g. because of throttling or blizzard delays). You see his threat get stuck for a few seconds and then he probably lacks behind 2-3 seconds and has more threat than you. How did the situation look on his threat meter? If it's a sync issue he should have been higher than you on his own threat meter.

Are both of you running the most recent version? That tried to reduce the amount of throttling issues.

**Comment by Truank** [comment]
Both people were running the same version he stated his threat was behind
mine on his meter too.
The 2nd time it happened a different person, Moggrosh, gained threat who
also stated they were below me.
I don't have any VODs from Fhynxx though so I can't confirm.

**Comment by dfherr** [comment]
Can you link me logs?

**Comment by Truank** [comment]
This is the raid logs
The first 2 wipes on Vael were with using finkles.
After that I switched back to Quel and the meter felt more accurate.
https://classic.warcraftlogs.com/reports/axyh7kfwntZ3Hg1B/

**Comment by dfherr** [comment]
This is most likely an issue that came from missing/dodged/parried abilites still applying bonus threat incorrectly, this is fixed by now. I rewatched your video and saw a lot of yellow misses/dodge, which all incorrectly applied bonus threat. (Btw, you should use 6% with +5 weaponskill or 9% hit also as a tank ;))

**Comment by Truank** [comment]
My weapon skill for my dagger was 290ish at the time, but when testing
threat on our first pull it was still showing as way higher than what I was
getting with quel previously. Which is why I used it anyway at the time.
Didn't know that the meters didn't differentiate misses dodges and parries
from hits
